### ISSUE TITLE
Critical bug with layouts in newer log4js

### ISSUE THREAD

**Issue by morungos** [morungos/log4js-knex#4]
Just tried to deploy the new plugin and we get a nasty error:

```
[2018-10-31T10:26:59.018] [INFO] configuration - Reading configuration file: /Users/stuart/git/api-server/config.json
/Users/stuart/git/api-server/node_modules/log4js-knex/lib/log4js-knex.js:60
    const formatted = layout(loggingEvent);
                      ^

TypeError: layout is not a function
    at writeEvent (/Users/stuart/git/api-server/node_modules/log4js-knex/lib/log4js-knex.js:60:23)
    at /Users/stuart/git/api-server/node_modules/log4js/lib/appenders/logLevelFilter.js:9:7
    at categoryAppenders.forEach (/Users/stuart/git/api-server/node_modules/log4js/lib/log4js.js:42:5)
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (/Users/stuart/git/api-server/node_modules/log4js/lib/log4js.js:41:21)
    at listeners.forEach.l (/Users/stuart/git/api-server/node_modules/log4js/lib/clustering.js:16:26)
    at Array.forEach (<anonymous>)
    at sendToListeners (/Users/stuart/git/api-server/node_modules/log4js/lib/clustering.js:16:13)
    at Object.send (/Users/stuart/git/api-server/node_modules/log4js/lib/clustering.js:78:7)
    at Logger._log (/Users/stuart/git/api-server/node_modules/log4js/lib/logger.js:56:16)
    at Logger.log (/Users/stuart/git/api-server/node_modules/log4js/lib/logger.js:45:12)
    at Logger.(anonymous function) [as info] (/Users/stuart/git/api-server/node_modules/log4js/lib/logger.js:84:10)
    at getConfiguration (/Users/stuart/git/api-server/src/service/lib/configuration.js:19:10)
    at Object.<anonymous> (/Users/stuart/git/api-server/src/service/lib/configuration.js:97:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by morungos** [comment]
Turns out the `messagePassThroughLayout` was suffixed in a way that is not very clear from, e.g.: https://github.com/log4js-node/log4js-node/blob/master/docs/layouts.md
